# Generated by Django 4.2.7 on 2026-06-09 00:59

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('PRESIDENTE', 'Presidente/Fundador'), ('DIRECTOR', 'Director'), ('SUBDIRECTOR', 'Subdirector'), ('JEFE_SECCION', 'Jefe de Sección'), ('MUSICO', 'Músico')], default='MUSICO', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth_usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banda', models.CharField(default='Banda de Música', max_length=200)),
                ('monto_por_evento', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('hora_limite_tardanza', models.TimeField(default=datetime.time(19, 5))),
                ('email_director', models.EmailField(blank=True, max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('uniforme', models.CharField(choices=[('GALA', 'Uniforme de Gala'), ('DIARIO', 'Uniforme Diario'), ('VIAJE', 'Uniforme de Viaje'), ('VELADA', 'Uniforme de Velada'), ('OTRO', 'Otro (especificar)')], default='DIARIO', max_length=20)),
                ('uniforme_personalizado', models.CharField(blank=True, help_text="Especificar si elige 'Otro'", max_length=300)),
                ('fecha_hora_cita', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de cita')),
                ('lugar_concentracion', models.CharField(blank=True, max_length=300)),
                ('detalles_uniforme', models.TextField(blank=True, help_text='Descripción escrita del uniforme')),
                ('responsable', models.CharField(choices=[('DIRECTOR', 'Director'), ('SUBDIRECTOR', 'Subdirector'), ('PRESIDENTE', 'Presidente/Fundador')], default='DIRECTOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_hora_cita'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('DASHBOARD', 'Dashboard Principal'), ('MUSICOS', 'Gestión de Músicos'), ('EVENTOS', 'Gestión de Eventos'), ('DESCUENTOS', 'Registrar Descuentos'), ('ADELANTOS', 'Registrar Adelantos'), ('LIQUIDACIONES', 'Generar Liquidaciones'), ('CANASTON', 'Canastón - Rendimiento'), ('FINANCIAMIENTO', 'Financiamiento'), ('HISTORIAL_DESCUENTOS', 'Ver Historial de Descuentos'), ('HISTORIAL_CONTRATOS', 'Ver Historial de Contratos'), ('ADMIN_USUARIOS', 'Administración de Usuarios')], max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
            },
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9-]+$', 'Solo se permiten números y guiones')], verbose_name='Documento de Identidad')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True)),
                ('talla_camisa', models.CharField(blank=True, max_length=10)),
                ('talla_chamarra', models.CharField(blank=True, max_length=10)),
                ('numero_calzado', models.CharField(blank=True, max_length=10)),
                ('instrumento', models.CharField(choices=[('TROMPETA', 'Trompeta'), ('TROMBON', 'Trombón'), ('SAXOFON', 'Saxofón'), ('CLARINETE', 'Clarinete'), ('FLAUTA', 'Flauta'), ('TUBA', 'Tuba'), ('BARITONO', 'Barítono'), ('BOMBO', 'Bombo'), ('TAMBOR', 'Tambor'), ('PLATILLOS', 'Platillos'), ('PERCUSION', 'Percusión General'), ('OTRO', 'Otro')], max_length=20)),
                ('nivel', models.CharField(choices=[('PRINCIPIANTE', 'Principiante'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado'), ('MAESTRO', 'Maestro')], default='INTERMEDIO', max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil')),
                ('orden', models.PositiveIntegerField(blank=True, default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_musico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Músico',
                'verbose_name_plural': 'Músicos',
                'ordering': ['orden', 'apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='RendimientoMusico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_lealtad', models.IntegerField(default=0)),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('puntualidad_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('antiguedad_meses', models.IntegerField(default=0)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('musico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rendimiento', to='gestion_banda.musico')),
            ],
            options={
                'verbose_name': 'Rendimiento de Músico',
                'verbose_name_plural': 'Rendimientos de Músicos',
                'ordering': ['-score_lealtad'],
            },
        ),
        migrations.CreateModel(
            name='PlanillaLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('eventos', models.ManyToManyField(blank=True, related_name='planillas', to='gestion_banda.evento')),
            ],
            options={
                'verbose_name': 'Planilla de Liquidación',
                'verbose_name_plural': 'Planillas de Liquidación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salario Base')),
                ('descuentos_totales', models.DecimalField(decimal_places=2, default=0, help_text='Suma de descuentos aprobados', max_digits=10)),
                ('adelantos_totales', models.DecimalField(decimal_places=2, default=0, help_text='Suma de adelantos aprobados', max_digits=10)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, help_text='salario_base - descuentos + adelantos', max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('fecha_liquidacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion_banda.musico')),
                ('planilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion_banda.planillaliquidacion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_liquidacion'],
            },
        ),
        migrations.CreateModel(
            name='JefeSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('TROMPETA', 'Trompeta'), ('TROMBON', 'Trombón'), ('SAXOFON', 'Saxofón'), ('CLARINETE', 'Clarinete'), ('FLAUTA', 'Flauta'), ('TUBA', 'Tuba'), ('BARITONO', 'Barítono'), ('BOMBO', 'Bombo'), ('TAMBOR', 'Tambor'), ('PLATILLOS', 'Platillos'), ('PERCUSION', 'Percusión General'), ('OTRO', 'Otro')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_nombramiento', models.DateField(default=django.utils.timezone.localdate)),
                ('musico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jefe_seccion', to='gestion_banda.musico')),
            ],
            options={
                'verbose_name': 'Jefe de Sección',
                'verbose_name_plural': 'Jefes de Sección',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='convocados',
            field=models.ManyToManyField(blank=True, related_name='eventos_convocados', to='gestion_banda.musico'),
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='gestion_banda.musico')),
            ],
            options={
                'verbose_name': 'Deuda/Financiamiento',
                'verbose_name_plural': 'Deudas/Financiamientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ContratoMusico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_diario', models.DecimalField(decimal_places=2, help_text='Monto base por día para este músico en este evento', max_digits=10, verbose_name='Monto Diario Base')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Motivo de la asignación personalizada')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, help_text='Director/Subdirector que aprobó este contrato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestion_banda.evento')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='gestion_banda.musico')),
            ],
            options={
                'verbose_name': 'Contrato de Músico',
                'verbose_name_plural': 'Contratos de Músicos',
                'unique_together': {('musico', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='AbonoDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='gestion_banda.deuda')),
                ('planilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_deuda', to='gestion_banda.planillaliquidacion')),
            ],
            options={
                'verbose_name': 'Abono de Deuda',
                'verbose_name_plural': 'Abonos de Deudas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_asignaciones', to='gestion_banda.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_personales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Módulo',
                'verbose_name_plural': 'Usuarios Módulos',
                'unique_together': {('usuario', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='RolModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('PRESIDENTE', 'Presidente/Fundador'), ('DIRECTOR', 'Director'), ('SUBDIRECTOR', 'Subdirector'), ('JEFE_SECCION', 'Jefe de Sección'), ('MUSICO', 'Músico')], max_length=20)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_asignaciones', to='gestion_banda.modulo')),
            ],
            options={
                'verbose_name': 'Rol Módulo',
                'verbose_name_plural': 'Rol Módulos',
                'unique_together': {('rol', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleMontoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha específica del evento')),
                ('monto_asignado', models.DecimalField(decimal_places=2, help_text='Monto específico para esta fecha', max_digits=10, verbose_name='Monto Asignado')),
                ('motivo_variacion', models.TextField(blank=True, help_text='Motivo de la variación del monto')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montos_diarios_aprobados', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_diarios', to='gestion_banda.contratomusico')),
            ],
            options={
                'verbose_name': 'Detalle de Monto Diario',
                'verbose_name_plural': 'Detalles de Montos Diarios',
                'unique_together': {('contrato', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField(help_text='Descripción detallada de la falta')),
                ('fecha_falta', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('APP_MOVIL', 'App Móvil'), ('FRONTEND', 'Frontend')], default='FRONTEND', max_length=20)),
                ('estado', models.CharField(choices=[('APROBADA', 'Aprobada'), ('LIQUIDADA', 'Liquidada en Pago')], default='APROBADA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('jefe_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_aplicados', to='gestion_banda.jefeseccion')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='gestion_banda.musico')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['-fecha_falta'],
                'indexes': [models.Index(fields=['musico', '-fecha_falta'], name='gestion_ban_musico__f3a8ee_idx'), models.Index(fields=['jefe_seccion', '-fecha_falta'], name='gestion_ban_jefe_se_ebf158_idx')],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('TARDANZA', 'Tardanza'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Justificado')], default='AUSENTE', max_length=20)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_asistencia', models.DateField(default=django.utils.timezone.localdate, help_text='Fecha específica de asistencia (para eventos multi-día)')),
                ('monto_acordado', models.DecimalField(decimal_places=2, default=0, help_text='Pago asignado por el directorio para este día específico', max_digits=10, verbose_name='Monto Acordado')),
                ('liquidado', models.BooleanField(default=False, help_text='Indica si este día ya fue pagado')),
                ('contrato', models.ForeignKey(blank=True, help_text='Contrato personalizado para este evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_banda.contratomusico')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_banda.evento')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_banda.musico')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('musico', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='Adelanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('origen', models.CharField(choices=[('APP_MOVIL', 'App Móvil'), ('FRONTEND', 'Frontend')], default='FRONTEND', max_length=20)),
                ('estado', models.CharField(choices=[('APROBADA', 'Aprobada'), ('LIQUIDADA', 'Liquidada en Pago')], default='APROBADA', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='gestion_banda.contratomusico')),
                ('musico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adelantos', to='gestion_banda.musico')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adelantos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adelanto',
                'verbose_name_plural': 'Adelantos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['musico', '-fecha'], name='gestion_ban_musico__77a79f_idx')],
            },
        ),
    ]
