# Generated by Django 4.2.7 on 2026-06-09 05:22

from django.db import migrations, models
import gestion_banda.models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion_banda", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracionsistema",
            name="hora_limite_tardanza",
            field=models.TimeField(default=gestion_banda.models.default_hora_tardanza),
        ),
    ]
